maximum:
  name: 50
  address: 255
  phone: 11
  password: 16
  email: 255
  content: 255
  avatar: 32
minimum:
  name: 10
  address: 10
  phone: 11
  password: 6
  email: 6
  content: 50
  avatar: 32
default:
  user_id: 1
  recently: 12
  round: 1
  static_page:
    about: "pages/about"
    why_us: "pages/why-us"
    ship_cod: "pages/ship-cod"
    warning: "pages/warning"
  user:
    activated: 1
    not_activated: 0
  role:
    admin: 0
    editor: 1
    user: 2
  order:
    created: 0
    waiting: 1
    finished: 2
    min: 1
  order_detail:
    ready: 1
    not_ready: 0
  suggest_product:
    processed: 0
    waiting: 1
  quantity: 1
  product:
    image_empty: "empty_avatar.png"
    zero_price: 0
    increase_view: 1
    zero_score: 0
    filter_type:
      sort_desc_prices: "sort_desc_prices"
      sort_asc_prices: "sort_asc_prices"
      sort_desc_quantity: "sort_desc_quantity"
      sort_asc_quantity: "sort_asc_quantity"
      sort_desc_names: "sort_desc_names"
      sort_asc_names: "sort_asc_names"
    row_header: 1
    image_size: 80
    image_size_show: "300"
    empty_image: "empty_avatar.png"
    recently: 12
    link_file_import_products: "/shared/import_products_template.xlsx"
    number_of_order: 0
    number_of_view: 0
    top_new_products: 8
    top_order_products: 8
    recently_view_products: 8
    same_category: 10
    round: 1
    min_product: 0
    quantity_cart_item: 1
minrate: 1
maxrate: 5
ratestep: 0.1
per_page:
  users: 5
  suggest: 5
  product: 3
  order: 5
  min_product: 1
  catalog: 5
  num_row_per_page: 5
suggest_products:
  image:
    size: 64
    width: 64
    heigh: 64
  catalog: 5
devise:
  registrations: "registrations"
  passwords: "passwords"
  sessions: "sessions"
  confirmations: "confirmations"
  unlocks: "unlocks"
